### ISSUE TITLE
Error Upgrading From 1.0.3 -> 2x

### ISSUE THREAD

**Issue by donaldwasserman** [pzuraq/ember-cli-babel-polyfills#10]
Hi there - 

I upgraded from 1.0.3 -> 2.0 (with `ember-cli-babel` `7.11.0`) and get this error: 

```
Build Error (broccoli-persistent-filter:TransformAmd) in output/chunk1.js

ember-cli-babel-polyfills: unable to remap: chunk1.js
```

Not exactly if this is a problem just with this specific app or elsewhere or I'm missing something else. 

Here's the full stack trace: 

```
  - stack: Error: ember-cli-babel-polyfills: unable to remap: chunk1.js
    at TransformAmd.processString (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/lib/transform-amd.js:25:13)
    at resolve (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/lib/strategies/default.js:10:19)
    at initializePromise (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:995:33)
    at Object.processString (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/lib/strategies/default.js:9:18)
    at Processor.processString (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/lib/processor.js:19:27)
    at resolve (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/index.js:353:16)
    at initializePromise (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:995:33)
    at invoke (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/index.js:352:10)
    at TransformAmd.Filter.processFile (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/index.js:371:16)
    at Promise.resolve.then (/Users/djwasserman/projects/groundswell/frontend/node_modules/ember-cli-babel-polyfills/node_modules/broccoli-persistent-filter/index.js:337:21)
    at tryCatcher (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/djwasserman/projects/groundswell/frontend/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by LuisAverhoff** [comment]
@donaldwasserman Take a look at #9 Installing core-js as a dependency fixed the issue.

**Comment by donaldwasserman** [comment]
@LuisAverhoff Thanks - I'll give that a shot and report back.

**Comment by pzuraq** [comment]
Just to note, that is not a recommended solution, I haven't had time to dig in here but the intent was that `core-js` should have been included along with this addon.

**Comment by pzuraq** [comment]
This should have been fixed in v2.0.1, can you let me know if you're still seeing this issue? Thanks for the report 😄

**Comment by LuisAverhoff** [comment]
@pzuraq Thanks for the update, will try it out some time next week and get back to you.

**Comment by LuisAverhoff** [comment]
Yep, v2.0.1 helped resolve the issue for me.

**Comment by acorncom** [comment]
Looks like this can be closed
